[package]
name = "rbc"
version = "0.1.0"
edition = "2021"

[dependencies]
boolean_expression = "0.4.4"
clap = { version = "4.4.6", features = ["derive"] }
nom = "7.1.3"
lalrpop-util = { version = "0.20.0", features = ["lexer", "unicode"] }

[build-dependencies]
lalrpop = "0.20.0"
